import 'dart:ui';
import 'package:flutter/material.dart';
import '../../core/app_export.dart';

String _appTheme = "primary";

/// Helper class for managing themes and colors.
class ThemeHelper {
  // A map of custom color themes supported by the app
  Map<String, PrimaryColors> _supportedCustomColor = {
    'primary': PrimaryColors()
  };

// A map of color schemes supported by the app
  Map<String, ColorScheme> _supportedColorScheme = {
    'primary': ColorSchemes.primaryColorScheme
  };

  /// Changes the app theme to [_newTheme].
  void changeTheme(String _newTheme) {
    _appTheme = _newTheme;
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors _getThemeColors() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedCustomColor.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    return _supportedCustomColor[_appTheme] ?? PrimaryColors();
  }

  /// Returns the current theme data.
  ThemeData _getThemeData() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedColorScheme.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    var colorScheme =
        _supportedColorScheme[_appTheme] ?? ColorSchemes.primaryColorScheme;
    return ThemeData(
      visualDensity: VisualDensity.standard,
      colorScheme: colorScheme,
      textTheme: TextThemes.textTheme(colorScheme),
      scaffoldBackgroundColor: appTheme.whiteA700,
      outlinedButtonTheme: OutlinedButtonThemeData(
        style: OutlinedButton.styleFrom(
          backgroundColor: Colors.transparent,
          side: BorderSide(
            color: appTheme.gray40001,
            width: 1.h,
          ),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(4.h),
          ),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      dividerTheme: DividerThemeData(
        thickness: 1,
        space: 1,
        color: colorScheme.onPrimaryContainer,
      ),
    );
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors themeColor() => _getThemeColors();

  /// Returns the current theme data.
  ThemeData themeData() => _getThemeData();
}

/// Class containing the supported text theme styles.
class TextThemes {
  static TextTheme textTheme(ColorScheme colorScheme) => TextTheme(
        bodyLarge: TextStyle(
          color: appTheme.gray800,
          fontSize: 16.fSize,
          fontFamily: 'Open Sans',
          fontWeight: FontWeight.w400,
        ),
        bodyMedium: TextStyle(
          color: appTheme.gray500,
          fontSize: 14.fSize,
          fontFamily: 'Open Sans',
          fontWeight: FontWeight.w400,
        ),
        bodySmall: TextStyle(
          color: appTheme.gray60001,
          fontSize: 12.fSize,
          fontFamily: 'Open Sans',
          fontWeight: FontWeight.w400,
        ),
        titleLarge: TextStyle(
          color: appTheme.gray900,
          fontSize: 20.fSize,
          fontFamily: 'Open Sans',
          fontWeight: FontWeight.w600,
        ),
        titleMedium: TextStyle(
          color: colorScheme.primaryContainer,
          fontSize: 16.fSize,
          fontFamily: 'Open Sans',
          fontWeight: FontWeight.w700,
        ),
        titleSmall: TextStyle(
          color: appTheme.gray40001,
          fontSize: 15.fSize,
          fontFamily: 'Open Sans',
          fontWeight: FontWeight.w700,
        ),
      );
}

/// Class containing the supported color schemes.
class ColorSchemes {
  static final primaryColorScheme = ColorScheme.light(
    // Primary colors
    primary: Color(0XFF4E97FE),
    primaryContainer: Color(0XFF262626),
    secondary: Color(0XFF262626),
    secondaryContainer: Color(0XFF4E97FE),
    tertiary: Color(0XFF262626),
    tertiaryContainer: Color(0XFF4E97FE),

    // Background colors
    background: Color(0XFF262626),

    // Surface colors
    surface: Color(0XFF262626),
    surfaceTint: Color(0XFF001B3D),
    surfaceVariant: Color(0XFF4E97FE),

    // Error colors
    error: Color(0XFF001B3D),
    errorContainer: Color(0X3F000000),
    onError: Color(0XFF929292),
    onErrorContainer: Color(0XFF2E2E2E),

    // On colors(text colors)
    onBackground: Color(0XFFE3E2E6),
    onInverseSurface: Color(0XFF929292),
    onPrimary: Color(0XFF001B3D),
    onPrimaryContainer: Color(0XFFE3E2E6),
    onSecondary: Color(0XFFE3E2E6),
    onSecondaryContainer: Color(0XFF001B3D),
    onTertiary: Color(0XFFE3E2E6),
    onTertiaryContainer: Color(0XFF001B3D),

    // Other colors
    outline: Color(0XFF001B3D),
    outlineVariant: Color(0XFF262626),
    scrim: Color(0XFF262626),
    shadow: Color(0XFF001B3D),

    // Inverse colors
    inversePrimary: Color(0XFF262626),
    inverseSurface: Color(0XFF001B3D),

    // Pending colors
    onSurface: Color(0XFFE3E2E6),
    onSurfaceVariant: Color(0XFF001B3D),
  );
}

/// Class containing custom colors for a primary theme.
class PrimaryColors {
  // Amber
  Color get amber600 => Color(0XFFFFB700);

  // BlueGray
  Color get blueGray400 => Color(0XFF868686);
  Color get blueGray40001 => Color(0XFF888888);

  // DeepPurple
  Color get deepPurpleA200 => Color(0XFF795CF0);

  // Gray
  Color get gray400 => Color(0XFFBBBBBB);
  Color get gray40001 => Color(0XFFC7C6CA);
  Color get gray40002 => Color(0XFFC5C6D0);
  Color get gray50 => Color(0XFFF8F9FF);
  Color get gray500 => Color(0XFF909094);
  Color get gray600 => Color(0XFF858585);
  Color get gray60001 => Color(0XFF848484);
  Color get gray800 => Color(0XFF46474A);
  Color get gray900 => Color(0XFF202020);
  Color get gray90001 => Color(0XFF1A1C1E);

  // Red
  Color get red900 => Color(0XFFBA1A1A);

  // White
  Color get whiteA700 => Color(0XFFFFFFFF);
}

PrimaryColors get appTheme => ThemeHelper().themeColor();
ThemeData get theme => ThemeHelper().themeData();
